---
title: "BasketballProject"
author: "Mason Ogden"
date: "December 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(plotly)
```


```{r read data}
#test_data <- read.csv("https://www.dropbox.com/s/u3oijk3eh1oxm3q/BasketballData.csv?dl=1")
#data <- data %>%
#  select(Rk:X3P_Percent) %>%
#  rename(three_p_made = X3P_Made,
#         three_p_attempted = X3P_Attempted, 
#         three_p_percent = X3P_Percent)

```

```{r function for calcuating win/loss}
get_game_wl <- function(data) {
  win_count <- 0
  loss_count <- 0
  wl_vec <- c()
  for (i in 1:nrow(data)) {
    if (data[i, 4] == "W") {
      win_count = win_count + 1
    }
    else {
      loss_count = loss_count + 1
    }
    if (loss_count == 0) {
      wl_vec <- c(wl_vec, NA)
    }
    else {
      wl_vec <- c(wl_vec, win_count / loss_count)
    }
  }
  
  wl_vec
}
```


```{r read in and merge data}

start_path <- "C:/Users/Mason/Desktop/Git Repositories/BasketballProject/GameData/"

all_data <- data.frame(stringsAsFactors=FALSE)

file_name_list <- list.files("C:/Users/Mason/Desktop/Git Repositories/BasketballProject/GameData/")
for (i in 1:length(file_name_list)) {
  current_data <- read.table(str_c(start_path, file_name_list[i]), header=TRUE, sep=",",
                             stringsAsFactors = FALSE) %>%
    select(1:24, -Rk, -X)
  win_loss <- current_data %>%
    get_game_wl
  current_data <- current_data %>%
    mutate(win_loss = win_loss,
           team = str_remove(file_name_list[i], pattern=".txt"))
  all_data <- bind_rows(all_data, current_data)
    
  
}
```

```{r}
all_data <- read.csv("https://www.dropbox.com/s/ebj4qfc2lru2u4e/game_data.csv?dl=1")
```


```{r get most recent win/loss for each team}
end_data <- all_data %>%
  group_by(team) %>%
  summarize(G = max(G)) %>%
  inner_join(all_data, by = c("team", "G")) %>%
  select(team, G, win_loss)

top_3_teams <- end_data %>%
  top_n(3, win_loss) %>%
  pull(team)
```

```{r plotly settings}
font_settings <- list(
  family = "Courier New, monospace",
  size = 18,
  color = "#7f7f7f"
)
x_settings <- list(
  title = "Games Played",
  titlefont = font_settings
)
y_settings <- list(
  title = "Win/Loss Ratio",
  titlefont = font_settings
)

all_data %>%
  filter(team %in% top_3_teams) %>%
  plot_ly(x=~G, y=~win_loss,
          type="scatter", mode="lines",
          text = ~paste(team,
                  "<br>", "W/L: ", round(win_loss, digits=2),
                  "<br>", "Gm: ", G),
          hoverinfo='text', color=~team) %>%
  layout(title="Game-to-Game Win/Loss percentage for the Top 3 teams in the NBA (as of 12/14/19)",
         xaxis=x_settings, yaxis=y_settings)
```

